/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author ACER
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        email = new javax.swing.JLabel();
        emailfield = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        passwordfield = new javax.swing.JTextField();
        signin = new javax.swing.JButton();
        forgotpassword = new javax.swing.JButton();
        donthaveapassword = new javax.swing.JLabel();
        registerhere = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        panel.setBackground(new java.awt.Color(26, 26, 31));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        title.setForeground(new java.awt.Color(204, 204, 0));
        title.setText("NEPAL RESTAURANT MANAGEMENT SYSTEM");
        panel.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 21, 330, 70));

        body.setBackground(new java.awt.Color(26, 26, 31));
        body.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("E-mail");

        emailfield.addActionListener(this::emailfieldActionPerformed);

        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password");

        signin.setText("SIGN IN");

        forgotpassword.setBackground(new java.awt.Color(0, 0, 0));
        forgotpassword.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        forgotpassword.setForeground(new java.awt.Color(204, 204, 0));
        forgotpassword.setText("FORGOT PASSWORD?");
        forgotpassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 0)));
        forgotpassword.addActionListener(this::forgotpasswordActionPerformed);

        donthaveapassword.setBackground(new java.awt.Color(0, 0, 0));
        donthaveapassword.setForeground(new java.awt.Color(255, 255, 255));
        donthaveapassword.setText("Don't have an account ?");

        registerhere.setBackground(new java.awt.Color(0, 0, 0));
        registerhere.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        registerhere.setForeground(new java.awt.Color(204, 204, 0));
        registerhere.setText("REGISTER HERE");
        registerhere.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 0)));
        registerhere.addActionListener(this::registerhereActionPerformed);

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(forgotpassword)
                    .addComponent(passwordfield, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailfield, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(bodyLayout.createSequentialGroup()
                            .addComponent(donthaveapassword)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(registerhere, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(signin, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(signin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forgotpassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(donthaveapassword)
                    .addComponent(registerhere))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        panel.add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 330, 250));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        getContentPane().add(panel);
        panel.setBounds(0, 0, 550, 400);

        setBounds(0, 0, 564, 403);
    }// </editor-fold>//GEN-END:initComponents

    private void emailfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailfieldActionPerformed

    private void forgotpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forgotpasswordActionPerformed

    private void registerhereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerhereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerhereActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JLabel donthaveapassword;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailfield;
    private javax.swing.JButton forgotpassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel password;
    private javax.swing.JTextField passwordfield;
    private javax.swing.JButton registerhere;
    private javax.swing.JButton signin;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    public void AddLoginListner(ActionListener listener){
        signin.addActionListener(listener);
        
    }
    public javax.swing.JTextField getPasswordText(){
        return passwordfield;
    }
    public javax.swing.JTextField getUsernameText(){
        return emailfield;
    }
}
